version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - salamander
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - salamander
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - salamander
networks:
  salamander:
