version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - salamander
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - salamander
    volumes:
      - ./backend:/app
      - ./backend/logs.log:/app/logs.log
    environment:
      #- MONGO_URI=mongodb://admin:pass@mongo:27017/imageDatabase
      - MONGO_URI=mongodb://mongo:27017/imageDatabase
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/data/db/
    networks:
      - salamander
networks:
  salamander:
    driver: bridge
