version: '3.1'

## the idea is to get backend working with mongodb credentials, so that I can use mongo-express

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
      #- "80:80"
    networks:
      - salamander
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - salamander
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./backend/logs.log:/app/logs.log
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    command: [--auth]
    volumes:
      - ./data:/data/db/
      - ./init.js:/docker-entrypoint-initdb.d/init.js  # Mount the script
    networks:
      - salamander
    #command: mongod
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - salamander
      
networks:
  salamander:
    driver: bridge
