version: '3.1'

## the idea is to get backend working with mongodb credentials, so that I can use mongo-express

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile-dev
    restart: always
    ports:
      #- "3000:3000"
      - "80:80"
    networks:
      - salamander
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - salamander
    volumes:
      - ./backend:/app
      - ./backend/logs.log:/app/logs.log
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=pass
      - MONGO_AUTH_SOURCE=admin
      - MONGO_SERVICE_NAME=mongo
      - MONGO_PORT=27017
      - DATABASE_NAME=imageDatabase
      - MONGO_URI=mongodb://admin:pass@mongo:27017/imageDatabase
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    #environment:
    #  - MONGO_INITDB_DATABASE=imageDatabase
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/data/db/
      - ./init.js:/docker-entrypoint-initdb.d/init.js  # Mount the script
    networks:
      - salamander
    #command: mongod
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    networks:
      - salamander
      
networks:
  salamander:
    driver: bridge
